# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    producer_collection_menu.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Service\Layout\Configurator\ProducerCollectionProductsBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    producer_collection_menu.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProducerCollectionMenuBoxController
        arguments: ['@producer.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer_collection_products.layout_box.configurator:
        class: WellCommerce\Bundle\CatalogBundle\Service\Layout\Configurator\ProducerCollectionMenuBoxConfigurator
        autowire: true
        tags:
            - { name: layout_box.configurator }

    producer_collection_products.layout_box.controller:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Box\ProducerCollectionProductsBoxController
        arguments: ['@producer.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer_collection.controller.front:
        class: WellCommerce\Bundle\CatalogBundle\Controller\Front\ProducerCollectionController
        arguments: ['@producer_collection.manager']
        calls:
            - [setContainer, ['@service_container']]

    producer_collection.storage:
        class: WellCommerce\Bundle\CatalogBundle\Request\Storage\ProducerCollectionStorage
